ci:
  skip: [cmake-generate-compile-commands, clang-tidy, doxygen-check]

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        name: Format source files (clang-format)
        types_or: [c++, c]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        name: check clang-tidy
        args:
          - -p=build
        files: ^(Source/|Exec/|Physics/)

  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.1.0 # Use the latest stable version of reuse-tool
    hooks:
      - id: reuse
        files: ^(Source/|Exec/|Physics/|Docs/)

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: ^(Source|Docs|Exec|Physics)/
        args: ["--ignore-words", ".codespellignore" ]        

  - repo: local
    hooks:
      - id: format-input-files
        name: Format input files (.options and .inputs)
        entry: ./FormatInputFiles.sh
        language: script
        files: \.(inputs|options)$
        pass_filenames: false


