#ifndef BLVERSION_H
#define BLVERSION_H

//
// $Id: BLVERSION.H,v 1.2 2007-05-24 23:54:48 tdsternberg Exp $
//

/*@ManDoc: The major version number of boxlib -- an integer.

           The BoxLib version number has the form:

               BL\_VERSION\_MAJOR.BL\_VERSION\_MINOR
*/
#define BL_VERSION_MAJOR 2

/*@ManDoc: The minor version number of boxlib -- an integer.

           The BoxLib version number has the form:

               BL\_VERSION\_MAJOR.BL\_VERSION\_MINOR
*/
#define BL_VERSION_MINOR 5

#endif /*BLVERSION_H*/
