/* chombo-discharge
 * Copyright © 2022 SINTEF Energy Research.
 * Please refer to Copyright.txt and LICENSE in the chombo-discharge root directory.
 */

/*!
  @file   CD_TracerParticlePhysics.H
  @brief  Documentation of Physics/TracerParticle namespace
  @author Robert Marskar
*/

#ifndef CD_TracerParticlePhysics_H
#define CD_TracerParticlePhysics_H

#include <CD_NamespaceHeader.H>

namespace Physics {
  /*!
    @brief Namespace for encapsulating physics code for tracer particles
  */
  namespace TracerParticle {
  }

} // namespace Physics

#include <CD_NamespaceFooter.H>

#endif
