#!/bin/bash
#
# Write a header file defining CD_GIT_HASH -- the git description of the chombo-discharge tree that
# is being compiled. Invoked from Lib/Definitions.make at makefile-parse time; the single argument
# is the full path of the header to write.
#
# The build must never depend on git being present. Every failure mode -- no git binary, a release
# tarball with no .git directory, a repository git refuses to touch (e.g. "dubious ownership"), a
# git version that does not understand the flags -- falls through to the string "unknown", and the
# script always exits 0 so that $(shell ...) cannot break the build.
#
# The header is rewritten only when its contents change. Chombo's dependency tracking is
# timestamp-based, so an unconditional rewrite would recompile the consuming object file on every
# single invocation of make.

set -u

header="${1:?usage: GenerateGitHash.sh <path to header>}"

# The tree to describe is the one this script lives in, which is DISCHARGE_HOME by construction.
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

gitHash="unknown"
if command -v git >/dev/null 2>&1 && git -C "${repo}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # --tags   : consider lightweight tags, not just annotated ones.
  # --always : fall back to the abbreviated commit hash when no tag is reachable. This is the normal
  #            case for a shallow CI checkout, which fetches no tags.
  # --dirty  : append "-dirty" when the working tree has uncommitted changes.
  described="$(git -C "${repo}" describe --tags --always --dirty 2>/dev/null)"

  if [ -n "${described}" ]; then
    # Tag names are nearly unconstrained, so sanitize before embedding the string in C++ source.
    gitHash="$(printf '%s' "${described}" | sed 's|[^A-Za-z0-9._+/~-]|_|g')"
  fi
fi

directory="$(dirname "${header}")"
mkdir -p "${directory}" || exit 0

tmp="$(mktemp "${header}.XXXXXX")" || exit 0

cat >"${tmp}" <<EOF
/*
 * SPDX-FileCopyrightText: 2021-2026 SINTEF Energy Research
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/**
 * @file   CD_GitHash.H
 * @brief  Generated file defining the git description of the compiled source tree
 * @author Robert Marskar
 * @details This file is generated by Lib/GenerateGitHash.sh at build time. Do not edit it, and do
 * not put it under version control.
 */

#ifndef CD_GITHASH_H
#define CD_GITHASH_H

#define CD_GIT_HASH "${gitHash}"

#endif
EOF

if cmp -s "${tmp}" "${header}"; then
  rm -f "${tmp}"
else
  # mktemp creates the file 0600, which would hide the header from anyone but the user who happened
  # to run make first -- a real scenario for a shared installation on a cluster.
  chmod 644 "${tmp}" 2>/dev/null
  mv -f "${tmp}" "${header}" || rm -f "${tmp}"
fi

exit 0
