#!/bin/sh

#
# Migration utility by DBS
#

find . \( -name \*.cpp -o -name \*.H \) -exec grep '^\(.*#.*[^_"]\)HDF5' {} \; -exec ./doit2 1 {} \;

find . \( -name \*.cpp -o -name \*.H \) -exec grep '^\(^[ \t]*#[^#]*[^_"A-Z]\)MPI\($\|[^_]\)' {} \; -exec ./doit2 2 {} \;

find . \( -name \*.cpp -o -name \*.H \) -exec grep 'The....Vector' {} \; -exec ./doit2 3 {} \;

find . \( -name \*.cpp -o -name \*.H \) -exec grep 'ENABLE_MEMORY_TRACKING' {} \; -exec ./doit2 4 {} \;
