/* chombo-discharge
 * Copyright © 2022 SINTEF Energy Research.
 * Please refer to Copyright.txt and LICENSE in the chombo-discharge root directory.
 */

/*!
  @file   CD_KMC.H
  @brief  Declaration of the Kinetic Monte Carlo namespace
  @author Robert Marskar
*/

#ifndef CD_KMC_H
#define CD_KMC_H

// Our includes
#include <CD_NamespaceHeader.H>

/*!
  @brief Namespace for encapsulating Kinetic Monte Carlo routines
*/
namespace KMC {

};

#include <CD_NamespaceFooter.H>
