#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _CONSTANTS_C_H_
#define _CONSTANTS_C_H_


#define zero     (0.0e0)
#define one      (1.0e0)
#define two      (2.0e0)
#define three    (3.0e0)
#define four     (4.0e0)
#define five     (5.0e0)
#define six      (6.0e0)
#define seven    (7.0e0)
#define eight    (8.0e0)
#define nine     (9.0e0)
#define ten     (10.0e0)
#define twelve  (12.0e0)
#define fifteen (15.0e0)
#define sixteen (16.0e0)
#define twenty  (20.0e0)
#define tenth   (0.100e0)
#define eighth  (0.125e0)
#define sixth   (1.000e0 /  6.000e0)
#define fourth  (0.250e0)
#define third   (1.000e0 /  3.000e0)
#define half    (0.500e0)
#define twothird  (2.000e0 /  3.000e0)
#define threehalf (1.5e0)
#define fivehalf (2.5e0)
#define Pi      (3.14159265358979323846e0)
#define tiny     (1.e-10)
#define small     (1.e-6)
#define thousandth (1.0e-3)
#define hundredth  (1.0e-2)
#define sixty      (6.0e1)
#define hundred    (1.0e2)
#define thousand   (1.0e3)

#define ZERO     (0.0e0)
#define ONE      (1.0e0)
#define TWO      (2.0e0)
#define THREE    (3.0e0)
#define FOUR     (4.0e0)
#define FIVE     (5.0e0)
#define SIX      (6.0e0)
#define SEVEN    (7.0e0)
#define EIGHT    (8.0e0)
#define NINE     (9.0e0)
#define TEN     (10.0e0)
#define TWELVE  (12.0e0)
#define FIFTEEN (15.0e0)
#define SIXTEEN (16.0e0)
#define TWENTY  (20.0e0)
#define TENTH   (0.100e0)
#define EIGHTH  (0.125e0)
#define SIXTH   (1.000e0 / 6.000e0)
#define FOURTH  (0.250e0)
#define THIRD   (1.000e0 / 3.000e0)
#define HALF    (0.500e0)
#define TWOTHIRD  (2.000e0 / 3.000e0)
#define THREEHALF (1.5e0)
#define FIVEHALF (2.5e0)
#define PI      (3.14159265358979323846e0)
#define TINY     (1.e-10)
#define SMALL     (1.e-6)
#define THOUSANDTH (1.0e-3)
#define HUNDREDTH  (1.0e-2)
#define SIXTY      (6.0e1)
#define HUNDRED    (1.0e2)
#define THOUSAND   (1.0e3)


#endif
