#!/bin/csh -f
touch src/.tempDummy
foreach i (src/CoordSys.H src/FourthOrderCoordSys.H src/FourthOrderCoordSys.cpp src/FourthOrderCoordSysF.ChF src/FourthOrderCoordSysF_F.H src/EdgeQuadrature.H src/GaussianQuadrature.H src/GaussianQuadrature.cpp  src/NewtonCotesQuadrature.H src/NewtonCotesQuadrature.cpp src/FaceGradientF.ChF src/FaceGradientF_F.H src/PointwiseDotProdF.ChF src/PointwiseDotProdF_F.H src/FCDivergenceF.ChF src/FCDivergenceF_F.H util/FourthOrderUtil.H util/FourthOrderUtil.cpp util/FourthOrderUtilF.ChF util/FourthOrderUtilF_F.H srcMultiBlock/NewCoordSys.H srcMultiBlock/NewCoordSys.cpp srcMultiBlock/NewFourthOrderCoordSys.H srcMultiBlock/NewFourthOrderCoordSys.cpp srcMultiBlock/VectorTransformation.H srcMultiBlock/VectorTransformation.cpp srcMultiBlock/SimpleDivergence.H srcMultiBlock/SimpleDivergence.cpp srcMultiBlock/TaylorCoeffsLSF.ChF srcMultiBlock/TaylorCoeffsLSF_F.H srcMultiBlock/MultiBlockLevelExchange.cpp srcMultiBlock/MultiBlockLevelExchange.H srcMultiBlock/MultiBlockLevelExchangeAverage.cpp srcMultiBlock/MultiBlockLevelExchangeAverage.H srcMultiBlock/MultiBlockLevelExchangeCenter.cpp srcMultiBlock/MultiBlockLevelExchangeCenter.H srcMultiBlock/MultiBlockLevelGeom.cpp srcMultiBlock/MultiBlockLevelGeom.H srcMultiBlock/IndicesTransformation.cpp srcMultiBlock/IndicesTransformation.H srcMultiBlock/MultiBlockCoordSys.cpp srcMultiBlock/MultiBlockCoordSys.H srcMultiBlock/BlockBoundary.cpp srcMultiBlock/BlockBoundary.H srcMultiBlock/SecondOrderGradientF.ChF srcMultiBlock/SecondOrderGradientF_F.H srcMultiBlock/CartesianCS.cpp srcMultiBlock/CartesianCS.H srcMultiBlock/newMappedGridIO.cpp srcMultiBlock/newMappedGridIO.H srcMultiBlock/BlockBaseRegister.cpp srcMultiBlock/BlockBaseRegister.H srcMultiBlock/BlockBaseRegisterF.ChF srcMultiBlock/BlockRegister.cpp srcMultiBlock/BlockRegister.H srcMultiBlock/MultiBlockUtil.cpp srcMultiBlock/MultiBlockUtil.H srcMultiBlock/MBMiscUtil.cpp srcMultiBlock/MBMiscUtil.H srcMultiBlock/SolveQR.F src/.tempDummy)
if (-e $i) mv -f $i  ../../lib/src/BoxTools;
end;
rm -f ../../lib/src/BoxTools/.tempDummy
foreach i (srcMultiBlock/SolveNormalEquations.F)
if (-e $i) mv -f $i  ../../lib/src/BaseTools;
end;

