name: Code integrity

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-code-format
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        directory: [Source, Physics, Geometries, Examples]

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: ${{ matrix.directory }}
          extensions: 'H, hpp, cpp'
          clangFormatVersion: 10
