name: Run tests (GCC)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env: 
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib
      DISCHARGE_HOME: ${{github.workspace}}

    steps:
      - name: Clone Chombo
        uses: actions/checkout@master
        with:
          repository: chombo-discharge/Chombo-3.3
          path: ./Chombo-3.3

      - name: Checkout chombo-discharge
        uses: actions/checkout@v2
        with:
          repository: chombo-discharge/chombo-discharge
          path: ./chombo-discharge


