name: TEST

on:
  pull_request:
    types: [push, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc    
  cancel-in-progress: true

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    env: 
      DISCHARGE_HOME: ${{github.workspace}}
      CHOMBO_HOME: ${{github.workspace}}/Chombo-3.3/lib

  GNU:
    needs: setup
    name: Install GNU dependencies
    steps:
      - sanity: Sanity check
        run: |
          echo ${{env.DISCHARGE_HOME}}
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev

  GNUU:
    needs: setup
    name: Install GNU dependencies
    steps:
      - sanity: Sanity check
        run: |
          echo ${{env.DISCHARGE_HOME}}
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev                    
